"""Esquema Postgres con Row Level Security.

La app y la importación comparten estas tablas. Todo registro que viene de
Slack lleva origin='slack' y el ts del mensaje original (slack_ts).

Hay dos conexiones:
  - DATABASE_URL: dueño de las tablas. La usan la importación y las
    migraciones. El dueño no pasa por RLS.
  - DAILY_APP_DATABASE_URL: rol de la app (daily_app por defecto), sin
    BYPASSRLS. Cada conexión declara quién es el usuario con
    set_user(email) y Postgres filtra las filas según las políticas.
"""
import os
import re

import psycopg2
import psycopg2.extras

SCHEMA = """
CREATE TABLE IF NOT EXISTS people (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slack_user_id TEXT UNIQUE,
    code          TEXT UNIQUE,               -- "LT", "NG"... del archivo de historia
    name          TEXT NOT NULL
);

-- Días de PTO. No rompen la racha de días seguidos ni la suman.
CREATE TABLE IF NOT EXISTS pto (
    person_id INTEGER NOT NULL REFERENCES people(id),
    day       TEXT NOT NULL,
    origin    TEXT NOT NULL,
    PRIMARY KEY (person_id, day)
);

-- Un día de Daily = un hilo "Daily Delivery —" (o un día en la app).
CREATE TABLE IF NOT EXISTS days (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day       TEXT NOT NULL UNIQUE,          -- YYYY-MM-DD, hora de Bogotá
    origin    TEXT NOT NULL,                 -- 'slack' | 'app'
    slack_ts  TEXT UNIQUE,                   -- ts del mensaje "Daily Delivery —"
    format    TEXT NOT NULL                  -- 'libre' | 'marcas' | 'app'
);

CREATE TABLE IF NOT EXISTS reports (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_id                INTEGER NOT NULL REFERENCES days(id),
    person_id             INTEGER NOT NULL REFERENCES people(id),
    origin                TEXT NOT NULL,     -- 'slack' | 'app'
    slack_ts              TEXT,              -- primer mensaje del reporte
    format                TEXT NOT NULL,     -- 'libre' | 'marcas' | 'app'
    raw_text              TEXT,              -- texto completo (siempre en 'libre')
    counts_for_rate       INTEGER NOT NULL DEFAULT 1,
    counts_for_compliance INTEGER NOT NULL DEFAULT 1,
    has_blockers_field    INTEGER NOT NULL DEFAULT 0,
    has_blockers          INTEGER NOT NULL DEFAULT 0,
    blockers_status       TEXT,              -- 'sin_bloqueos' | 'campo_ausente' | otro
    blockers_note         TEXT,
    UNIQUE (day_id, person_id)
);

-- Cada mensaje de Slack que forma parte de un reporte.
CREATE TABLE IF NOT EXISTS report_messages (
    slack_ts   TEXT PRIMARY KEY,
    report_id  INTEGER NOT NULL REFERENCES reports(id),
    text_hash  TEXT NOT NULL,
    raw_text   TEXT NOT NULL
);

-- section: 'ayer' (estado de lo de ayer) | 'hoy' (compromiso nuevo)
-- mark: 'hecho' | 'pendiente' | 'no_tocado' | NULL (en 'hoy' no hay marca)
CREATE TABLE IF NOT EXISTS commitments (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id     INTEGER NOT NULL REFERENCES reports(id),
    section       TEXT NOT NULL,
    text          TEXT NOT NULL,
    grp           TEXT,                      -- "BAHAMAS:", "Costa Rica:"
    mark          TEXT,
    mark_source   TEXT,                      -- 'emoji' | 'palabra' | 'manual'
    is_extra      INTEGER NOT NULL DEFAULT 0,
    note          TEXT,                      -- nota del archivo (marca original, etc.)
    due_date      TEXT,                      -- fecha de cierre declarada
    starting_point INTEGER NOT NULL DEFAULT 0, -- 1 = aparece como "Ayer" el primer día en la app
    file_streak   INTEGER,                   -- dias_seguidos_al_corte del archivo (referencia)
    monday_url    TEXT,
    monday_key    TEXT,                      -- "board:pulse" o "board"
    link_status   TEXT NOT NULL,             -- 'con_link' | 'sin_link'
    streak_days   INTEGER NOT NULL DEFAULT 1,
    streak_prev_id INTEGER REFERENCES commitments(id),
    origin        TEXT NOT NULL,             -- 'slack' | 'app'
    slack_ts      TEXT,
    line_key      TEXT,                      -- clave estable de la línea
    manual        INTEGER NOT NULL DEFAULT 0,
    UNIQUE (slack_ts, line_key)
);

CREATE TABLE IF NOT EXISTS operation_items (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id INTEGER NOT NULL REFERENCES reports(id),
    text      TEXT NOT NULL,
    origin    TEXT NOT NULL,
    slack_ts  TEXT,
    line_key  TEXT,
    manual    INTEGER NOT NULL DEFAULT 0,
    UNIQUE (slack_ts, line_key)
);

CREATE TABLE IF NOT EXISTS blockers (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id      INTEGER NOT NULL REFERENCES reports(id),
    text           TEXT NOT NULL,
    decision_level INTEGER,
    origin         TEXT NOT NULL,
    slack_ts       TEXT,
    line_key       TEXT,
    manual         INTEGER NOT NULL DEFAULT 0,
    UNIQUE (slack_ts, line_key)
);

-- Líneas (o mensajes enteros) que no se pudieron interpretar con seguridad.
CREATE TABLE IF NOT EXISTS review_items (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind          TEXT NOT NULL,             -- 'linea' | 'mensaje'
    slack_ts      TEXT NOT NULL,
    line_key      TEXT NOT NULL,
    day           TEXT NOT NULL,
    person_id     INTEGER REFERENCES people(id),
    report_id     INTEGER REFERENCES reports(id),
    section       TEXT,
    monday_url    TEXT,
    note          TEXT,
    raw_text      TEXT NOT NULL,
    reason        TEXT NOT NULL,
    status        TEXT NOT NULL DEFAULT 'pendiente', -- 'pendiente' | 'resuelto' | 'descartado'
    resolution    TEXT,                      -- JSON con lo que decidió el admin
    resolved_at   TEXT,
    stale         INTEGER NOT NULL DEFAULT 0, -- el mensaje original cambió
    UNIQUE (slack_ts, line_key)
);

CREATE TABLE IF NOT EXISTS import_runs (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at  TEXT NOT NULL,
    finished_at TEXT,
    status      TEXT NOT NULL,
    stats_json  TEXT
);

-- Quién entra a la app y con qué rol. El correo es el que entrega el login.
CREATE TABLE IF NOT EXISTS users (
    email     TEXT PRIMARY KEY,
    role      TEXT NOT NULL CHECK (role IN ('admin', 'member')),
    person_id INTEGER REFERENCES people(id)
);

-- Notas privadas del admin sobre cada persona. Solo las ve y edita su autor.
CREATE TABLE IF NOT EXISTS admin_notes (
    person_id    INTEGER NOT NULL REFERENCES people(id),
    author_email TEXT NOT NULL,
    body         TEXT NOT NULL DEFAULT '',
    updated_at   TEXT NOT NULL,
    PRIMARY KEY (person_id, author_email)
);

CREATE TABLE IF NOT EXISTS launch_approvals (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    approved_at   TEXT NOT NULL,
    import_run_id INTEGER NOT NULL REFERENCES import_runs(id),
    summary_json  TEXT NOT NULL
);
"""

# Tablas por tipo de acceso para RLS.
_PERSON_TABLES = ("reports", "pto")
_REPORT_CHILD_TABLES = ("commitments", "operation_items", "blockers", "report_messages")
_ADMIN_ONLY_TABLES = ("review_items", "import_runs", "launch_approvals")

RLS = """
CREATE OR REPLACE FUNCTION app_user_email() RETURNS text
    LANGUAGE sql STABLE AS
$$ SELECT nullif(current_setting('app.user_email', true), '') $$;

CREATE OR REPLACE FUNCTION app_is_admin() RETURNS boolean
    LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS
$$ SELECT EXISTS (SELECT 1 FROM users WHERE email = app_user_email() AND role = 'admin') $$;

CREATE OR REPLACE FUNCTION app_is_user() RETURNS boolean
    LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS
$$ SELECT EXISTS (SELECT 1 FROM users WHERE email = app_user_email()) $$;

CREATE OR REPLACE FUNCTION app_person_id() RETURNS integer
    LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS
$$ SELECT person_id FROM users WHERE email = app_user_email() $$;
"""


def _policies():
    out = []

    def table(t, *policies):
        out.append(f"ALTER TABLE {t} ENABLE ROW LEVEL SECURITY;")
        out.append(f"DROP POLICY IF EXISTS admin_all ON {t};")
        out.append(f"CREATE POLICY admin_all ON {t} FOR ALL USING (app_is_admin()) WITH CHECK (app_is_admin());")
        for name, sql in policies:
            out.append(f"DROP POLICY IF EXISTS {name} ON {t};")
            out.append(sql.format(t=t, name=name))

    table("users", ("own_row", "CREATE POLICY {name} ON {t} FOR SELECT USING (email = app_user_email());"))
    table("people", ("own_row", "CREATE POLICY {name} ON {t} FOR SELECT USING (id = app_person_id());"))
    table("days", ("read_all", "CREATE POLICY {name} ON {t} FOR SELECT USING (app_is_user());"))
    for t in _PERSON_TABLES:
        table(t, ("own_rows", "CREATE POLICY {name} ON {t} FOR ALL USING (person_id = app_person_id()) "
                              "WITH CHECK (person_id = app_person_id());"))
    for t in _REPORT_CHILD_TABLES:
        table(t, ("own_rows", "CREATE POLICY {name} ON {t} FOR ALL "
                              "USING (report_id IN (SELECT id FROM reports WHERE person_id = app_person_id())) "
                              "WITH CHECK (report_id IN (SELECT id FROM reports WHERE person_id = app_person_id()));"))
    for t in _ADMIN_ONLY_TABLES:
        table(t)
    # Notas privadas: solo el admin que las escribió. Otro admin tampoco las ve.
    out.append("ALTER TABLE admin_notes ENABLE ROW LEVEL SECURITY;")
    out.append("DROP POLICY IF EXISTS author_only ON admin_notes;")
    out.append("CREATE POLICY author_only ON admin_notes FOR ALL "
               "USING (author_email = app_user_email() AND app_is_admin()) "
               "WITH CHECK (author_email = app_user_email() AND app_is_admin());")
    return "\n".join(out)


def migrate(conn, app_role=None):
    """Crea tablas, funciones y políticas. Corre con la conexión del dueño."""
    from . import config
    app_role = app_role or config.APP_DB_ROLE
    conn.execute(SCHEMA)
    conn.execute(RLS)
    conn.execute(_policies())
    exists = conn.execute("SELECT 1 FROM pg_roles WHERE rolname = ?", (app_role,)).fetchone()
    if exists:
        conn.execute(f'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "{app_role}"')
        conn.execute(f'GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO "{app_role}"')
        conn.execute(f'GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO "{app_role}"')
    conn.commit()


def _translate(sql):
    """Placeholders estilo '?' a los de psycopg2."""
    return re.sub(r"\?", "%s", sql.replace("%", "%%"))


class Result:
    def __init__(self, cur):
        self._cur = cur

    def fetchone(self):
        return self._cur.fetchone() if self._cur.description else None

    def fetchall(self):
        return self._cur.fetchall() if self._cur.description else []

    def __iter__(self):
        return iter(self.fetchall())


class Conn:
    """Envoltorio pequeño para que el resto del código use ? y filas por nombre."""

    def __init__(self, raw):
        self.raw = raw

    def execute(self, sql, params=()):
        cur = self.raw.cursor(cursor_factory=psycopg2.extras.DictCursor)
        cur.execute(_translate(sql) if params else sql, tuple(params) if params else None)
        return Result(cur)

    def insert(self, sql, params=()):
        """INSERT que devuelve el id de la fila nueva."""
        return self.execute(sql.rstrip().rstrip(";") + " RETURNING id", params).fetchone()[0]

    def set_user(self, email):
        """Declara el usuario de esta conexión. RLS filtra según su rol."""
        self.execute("SELECT set_config('app.user_email', ?, false)", (email or "",))
        self.commit()

    def commit(self):
        self.raw.commit()

    def rollback(self):
        self.raw.rollback()

    def close(self):
        self.raw.close()


def connect(url=None):
    """Conexión del dueño (importación, migraciones)."""
    from . import config
    url = url or config.DATABASE_URL
    if not url:
        raise SystemExit("Falta DATABASE_URL (conexión de Postgres del dueño de las tablas).")
    return Conn(psycopg2.connect(url, client_encoding="utf8"))


def connect_app(email, url=None):
    """Conexión de la app como `email`. Siempre pasa por RLS."""
    from . import config
    url = url or config.APP_DATABASE_URL
    if not url:
        raise SystemExit("Falta DAILY_APP_DATABASE_URL (conexión de Postgres con el rol de la app).")
    conn = Conn(psycopg2.connect(url, client_encoding="utf8"))
    conn.set_user(email)
    return conn
