-- Daily Delivery · esquema (etapa 1)
-- Corre en Supabase (SQL Editor o `supabase db push`). En las pruebas corre
-- sobre Postgres con tests/supabase_stub.sql, que imita el esquema auth.

CREATE TABLE IF NOT EXISTS people (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slack_user_id TEXT UNIQUE,
    code          TEXT UNIQUE,               -- "LT", "NG"... del archivo de historia
    name          TEXT NOT NULL,
    country       TEXT NOT NULL DEFAULT 'CO' CHECK (country IN ('CO', 'CR'))  -- define sus festivos
);

-- Días de PTO. No rompen la racha de días seguidos ni la suman.
CREATE TABLE IF NOT EXISTS pto (
    person_id INTEGER NOT NULL REFERENCES people(id),
    day       TEXT NOT NULL,
    origin    TEXT NOT NULL,
    PRIMARY KEY (person_id, day)
);

-- Un día de Daily = un hilo "Daily Delivery —" (o un día en la app).
CREATE TABLE IF NOT EXISTS days (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day       TEXT NOT NULL UNIQUE,          -- YYYY-MM-DD, hora de Bogotá
    origin    TEXT NOT NULL,                 -- 'slack' | 'app'
    slack_ts  TEXT UNIQUE,                   -- ts del mensaje "Daily Delivery —"
    format    TEXT NOT NULL                  -- 'libre' | 'marcas' | 'app'
);

CREATE TABLE IF NOT EXISTS reports (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_id                INTEGER NOT NULL REFERENCES days(id),
    person_id             INTEGER NOT NULL REFERENCES people(id),
    origin                TEXT NOT NULL,     -- 'slack' | 'app'
    slack_ts              TEXT,              -- primer mensaje del reporte
    format                TEXT NOT NULL,     -- 'libre' | 'marcas' | 'app'
    raw_text              TEXT,              -- texto completo (siempre en 'libre')
    counts_for_rate       INTEGER NOT NULL DEFAULT 1,
    counts_for_compliance INTEGER NOT NULL DEFAULT 1,
    has_blockers_field    INTEGER NOT NULL DEFAULT 0,
    has_blockers          INTEGER NOT NULL DEFAULT 0,
    blockers_status       TEXT,              -- 'sin_bloqueos' | 'campo_ausente' | otro
    blockers_note         TEXT,
    UNIQUE (day_id, person_id)
);

-- Cada mensaje de Slack que forma parte de un reporte.
CREATE TABLE IF NOT EXISTS report_messages (
    slack_ts   TEXT PRIMARY KEY,
    report_id  INTEGER NOT NULL REFERENCES reports(id),
    text_hash  TEXT NOT NULL,
    raw_text   TEXT NOT NULL
);

-- section: 'ayer' (estado de lo de ayer) | 'hoy' (compromiso nuevo)
-- mark: 'hecho' | 'pendiente' | 'no_tocado' | NULL (en 'hoy' no hay marca)
CREATE TABLE IF NOT EXISTS commitments (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id     INTEGER NOT NULL REFERENCES reports(id),
    section       TEXT NOT NULL,
    text          TEXT NOT NULL,
    grp           TEXT,                      -- "BAHAMAS:", "Costa Rica:"
    mark          TEXT,
    mark_source   TEXT,                      -- 'emoji' | 'palabra' | 'manual'
    is_extra      INTEGER NOT NULL DEFAULT 0,
    note          TEXT,                      -- nota del archivo (marca original, etc.)
    due_date      TEXT,                      -- fecha de cierre declarada
    starting_point INTEGER NOT NULL DEFAULT 0, -- 1 = aparece como "Ayer" el primer día en la app
    file_streak   INTEGER,                   -- dias_seguidos_al_corte del archivo (referencia)
    monday_url    TEXT,
    monday_key    TEXT,                      -- "board:pulse" o "board"
    link_status   TEXT NOT NULL,             -- 'con_link' | 'sin_link'
    streak_days   INTEGER NOT NULL DEFAULT 1,
    streak_prev_id INTEGER REFERENCES commitments(id),
    origin        TEXT NOT NULL,             -- 'slack' | 'app'
    slack_ts      TEXT,
    line_key      TEXT,                      -- clave estable de la línea
    manual        INTEGER NOT NULL DEFAULT 0,
    UNIQUE (slack_ts, line_key)
);

CREATE TABLE IF NOT EXISTS operation_items (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id INTEGER NOT NULL REFERENCES reports(id),
    text      TEXT NOT NULL,
    origin    TEXT NOT NULL,
    slack_ts  TEXT,
    line_key  TEXT,
    manual    INTEGER NOT NULL DEFAULT 0,
    UNIQUE (slack_ts, line_key)
);

CREATE TABLE IF NOT EXISTS blockers (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id      INTEGER NOT NULL REFERENCES reports(id),
    text           TEXT NOT NULL,
    decision_level INTEGER CHECK (decision_level BETWEEN 1 AND 5),
    commitment_id  INTEGER REFERENCES commitments(id) ON DELETE SET NULL,  -- bloqueo ligado a un compromiso
    origin         TEXT NOT NULL,
    slack_ts       TEXT,
    line_key       TEXT,
    manual         INTEGER NOT NULL DEFAULT 0,
    UNIQUE (slack_ts, line_key)
);

-- Líneas (o mensajes enteros) que no se pudieron interpretar con seguridad.
CREATE TABLE IF NOT EXISTS review_items (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind          TEXT NOT NULL,             -- 'linea' | 'mensaje'
    slack_ts      TEXT NOT NULL,
    line_key      TEXT NOT NULL,
    day           TEXT NOT NULL,
    person_id     INTEGER REFERENCES people(id),
    report_id     INTEGER REFERENCES reports(id),
    section       TEXT,
    monday_url    TEXT,
    note          TEXT,
    raw_text      TEXT NOT NULL,
    reason        TEXT NOT NULL,
    status        TEXT NOT NULL DEFAULT 'pendiente', -- 'pendiente' | 'resuelto' | 'descartado'
    resolution    TEXT,                      -- JSON con lo que decidió el admin
    resolved_at   TEXT,
    stale         INTEGER NOT NULL DEFAULT 0, -- el mensaje original cambió
    UNIQUE (slack_ts, line_key)
);

CREATE TABLE IF NOT EXISTS import_runs (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at  TEXT NOT NULL,
    finished_at TEXT,
    status      TEXT NOT NULL,
    stats_json  TEXT
);

-- Quién entra a la app y con qué rol. El correo es el que entrega el login.
-- Lista permitida. Además del dominio, el correo tiene que estar aquí y activo.
CREATE TABLE IF NOT EXISTS users (
    email     TEXT PRIMARY KEY CHECK (email = lower(email)),
    role      TEXT NOT NULL CHECK (role IN ('admin', 'member')),
    person_id INTEGER REFERENCES people(id),
    active    BOOLEAN NOT NULL DEFAULT true
);

-- Festivos oficiales por país (se cargan con scripts/generar_festivos.py).
CREATE TABLE IF NOT EXISTS holidays (
    country TEXT NOT NULL CHECK (country IN ('CO', 'CR')),
    day     DATE NOT NULL,
    name    TEXT NOT NULL,
    PRIMARY KEY (country, day)
);

-- Días no hábiles propios de Forte. Aplican a todo el equipo. Los administra el admin.
CREATE TABLE IF NOT EXISTS forte_non_working_days (
    day        DATE PRIMARY KEY,
    name       TEXT NOT NULL,
    created_by TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Notas privadas del admin sobre cada persona. Solo las ve y edita su autor.
CREATE TABLE IF NOT EXISTS admin_notes (
    person_id    INTEGER NOT NULL REFERENCES people(id),
    author_email TEXT NOT NULL,
    body         TEXT NOT NULL DEFAULT '',
    updated_at   TEXT NOT NULL,
    PRIMARY KEY (person_id, author_email)
);

CREATE TABLE IF NOT EXISTS launch_approvals (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    approved_at   TEXT NOT NULL,
    import_run_id INTEGER NOT NULL REFERENCES import_runs(id),
    summary_json  TEXT NOT NULL
);
